# Site settings
title: BCEM
email: a.reyes@uniandes.edu.co
description: > # this means to ignore newlines until "baseurl:"
baseurl: ""
url: ""

collections:
  - team

plugins:
  - jekyll-polyglot
  - jekyll-paginate 
  - jekyll-redirect-from

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


# other info
twitter_username: bcem_uniandes
github_username:  BCEM-UniAndes
scholar_username: "hbXF8UEAAAAJ"
resgate_username: "Alejandro-Reyes-15"
orcid_username: "0000-0003-2907-3265"
publons_username: 
arxiv_username: 
biorxiv_username: 
linkedin_username: "alejandro-reyes-79a5a255"
mendeley_username: 
strava_username: 
maplocation: uniandes
author: "Alejandro Reyes"

# Map info -> check how to use
map_latitude: 4.601915
map_longitude: -74.066209
map_title: 'uniandes'
# map_apikey: "AIzaSyD3OqSEPg5iyHcriIfz-776IahCE3DhxZY"

#Polyglot -> Multilingual configuration
langsep: "|"
languages: ["en", "es"]
default_lang: "en"
exclude_from_localization: ["js", "images", "fonts", "flags", "css"]
parallel_localization: true
lang_from_path: true
whitelist:
  - jekyll-redirect-from

# Footer
footer1:
  en: 2023 BCEM. Powered by <a href="https://jekyllrb.com">Jekyll</a>
  es: 2023 BCEM. Impulsado por <a href="https://jekyllrb.com">Jekyll</a>
footer2:
  en: We are part of the <a href="https://cienciasbiologicas.uniandes.edu.co">Biological Sciences Department</a> at <a href="https://uniandes.edu.co/">Universidad de los Andes </a> in
  es: Somos parte del <a href="https://cienciasbiologicas.uniandes.edu.co">Departmento de Ciencias Biológicas</a> de la <a href="https://uniandes.edu.co/">Universidad de los Andes </a> en
footer3:
  en: Follow us
  es: Siguenos

# News panel
newsheader:
  en: News
  es: Noticias
newscontinue:
  en: see all News
  es: ver todas las Noticias