# Site settings
title: BIOMAC
email: om.santos@uniandes.edu.co
description: > # this means to ignore newlines until "baseurl:"
baseurl: ""
url: ""

collections:
  - team

plugins:
  - jekyll-polyglot
  - jekyll-paginate 
  - jekyll-redirect-from

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


# other info
twitter_username: 
github_username:  biomac-lab
scholar_username: 
resgate_username: 
orcid_username: 
publons_username: 
arxiv_username: 
biorxiv_username: 
linkedin_username: 
mendeley_username: 
strava_username: 
maplocation: uniandes
author: 

# Map info -> check how to use
map_latitude: 4.601915
map_longitude: -74.066209
map_title: 'uniandes'
# map_apikey: "AIzaSyD3OqSEPg5iyHcriIfz-776IahCE3DhxZY"

#Polyglot -> Multilingual configuration
langsep: "|"
languages: ["en", "es"]
default_lang: "es"
exclude_from_localization: ["js", "images", "fonts", "flags", "css"]
parallel_localization: true
lang_from_path: true
whitelist:
  - jekyll-redirect-from

# Header language menu
langmenu:
  en: Language
  es: Idioma

# Footer
footer1:
  en: 2024 BIOMAC. Powered by <a href="https://jekyllrb.com">Jekyll</a>
  es: 2024 BIOMAC. Impulsado por <a href="https://jekyllrb.com">Jekyll</a>
footer2:
  en: We are part of the <a href="https://ingbiomedica.uniandes.edu.co/">Biomedical Engineering</a>, <a href="https://cienciasbiologicas.uniandes.edu.co">Biological Sciences</a>, and <a href="https://matematicas.uniandes.edu.co/">Mathematics</a> Departments at <a href="https://uniandes.edu.co/">Universidad de los Andes </a> in
  es: Somos parte de los Departamento de <a href="https://ingbiomedica.uniandes.edu.co/">Ingeniería Biomédica</a>, <a href="https://cienciasbiologicas.uniandes.edu.co">Ciencias Biológicas</a> y <a href="https://matematicas.uniandes.edu.co/">Matemáticas</a> de la <a href="https://uniandes.edu.co/">Universidad de los Andes </a> en
footer3:
  en: Follow us
  es: Siguenos
footer4: 
  en: Contact
  es: Contacto

# News panel
newsheader:
  en: News
  es: Noticias
newscontinue:
  en: see all News
  es: ver todas las Noticias

# Team pages
interests:
  en: Interests
  es: Intereses
started:
  en: started
  es: desde